name: CI

on:
<<<<<<< HEAD
  workflow_dispatch:
  push:
    branches: [develop, 'feature/**', 'release/**', 'hotfix/**']
  pull_request:
=======
  push:
>>>>>>> bc049649fb6f351de156d37b9b9f3c408a8cd227
    branches:
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
=======
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
>>>>>>> bc049649fb6f351de156d37b9b9f3c408a8cd227
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
